FROM python:3.11-slim

WORKDIR /app
COPY . /app

# instalo solo lo necesario
RUN pip install --no-cache-dir -r requirements.txt

# # Asegurar carpeta para el CA del MySQL (si usas secret volume)
RUN mkdir -p /app/certs
RUN cp /app/db/DigiCertGlobalRootG2.crt.pem /app/certs/mysql-ca-cert

# Ejecutamos SOLO el job runner
ENTRYPOINT ["python", "jobs/matrixsap_job.py"]