# Usamos una imagen ligera de Python
FROM python:3.11-slim

# Evita que Python genere archivos .pyc y permite logs en tiempo real
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el resto del código del proyecto
COPY . /app

# Instalar dependencias del sistema necesarias para MySQL y compilación
# libmariadb-dev o default-libmysqlclient-dev son necesarios para SQLAlchemy/MySQL
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    default-libmysqlclient-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

# Copiar solo el archivo de requerimientos primero para aprovechar la caché de Docker
COPY requirements.txt .

# Instalar librerías de Python
RUN pip install --no-cache-dir -r requirements.txt

# # Asegurar carpeta para el CA del MySQL (si usas secret volume)
RUN mkdir -p /app/certs
RUN cp /app/db/DigiCertGlobalRootG2.crt.pem /app/certs/mysql-ca-cert

# El ENTRYPOINT apunta directamente a nuestro orquestador
ENTRYPOINT ["python", "jobs/conflict_job.py"]

