from .campo import Campo
from .actividad import Actividad
from .actividadtransaccion import ActividadTransaccion
from .regla import Regla
from .riesgo import Riesgo
from .transaccion import Transaccion
from .riesgoactividadtransaccion import RiesgoActividadTransaccion
from .sapcampo import SapCampo
from .sapobjeto import SapObjeto
from .sapobjetocampo import SapObjetoCampo
from .proceso import Proceso
from .appuser import AppUser
from .version import Version
from .sapnivelorganizacional import SapNivelOrganizacional
from .sapcampoorganizacional import SapCampoOrganizacional
from .sapobjetoproceso import SapObjetoProceso
from .sapcampoproceso import SapCampoProceso
from .usuariotransaccion import UsuarioTransaccion
from .sapusuario import SapUsuario
from .versionusuario import VersionUsuario
from .versionusuariorol import VersionUsuarioRol
from .saprolobjetoautorizacion import SapRolObjetoAutorizacion
from .versionusuarioobjeto import VersionUsuarioObjeto
from .usuariotransaccionrol import UsuarioTransaccionRol
from .sapusuarioperfil import SapUsuarioPerfil
from .sapperfilobjetoautorizacion import SapPerfilObjetoAutorizacion
from .sapusuariorol import SapUsuarioRol
from .sapobjetoautorizacion import SapObjetoAutorizacion
from .versionusuariotransaccion import VersionUsuarioTransaccion
from .usuario import Usuario
from .sapperfil import SapPerfil
from .sapautorizacion import SapAutorizacion
from .saprol import SapRol
from .sapusuariotipo import SapUsuarioTipo
from .saprolsubrol import SapRolSubRol
from .catalogo import Catalogo
from .appfiori import AppFiori
from .catalogoappfiori import CatalogoAppFiori
from .saprolcatalogo import SapRolCatalogo
from .generica import Generica
from .job import Job
from .conflicto import Conflicto
from .rendimiento import Rendimiento
from .matrizsap import MatrizSap
from .appuserrol import AppUserRol
from .rol import Rol